apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-skyworkz-news
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: true
spec:
  tls:
    - secretName: skyworkz-news-secret
  rules:
  - http:
      paths:
      - backend:
          serviceName: sampleapp
          servicePort: 80